-- Memory Seek 数据库初始化脚本
-- 合并 auth 和 photo 模块的所有表结构

-- ============================================
-- Auth 模块
-- ============================================

CREATE TABLE IF NOT EXISTS "auth_user"
(
    id                      BIGSERIAL PRIMARY KEY ,
    username                VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    password                VARCHAR(255) NOT NULL,
    nickname                VARCHAR(255) NOT NULL,
    avatar_file_id          VARCHAR(2000) NULL,
    inviter                 BIGINT NOT NULL,
    refresh_token           CHAR(32) NULL,
    refresh_token_expire_at TIMESTAMPTZ NULL,
    updated_at              TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    created_at              TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT user_username_index UNIQUE (username),
    CONSTRAINT user_email_index UNIQUE (email)
);

COMMENT ON TABLE "auth_user" IS '用户表';
COMMENT ON COLUMN "auth_user".id IS '主键ID';
COMMENT ON COLUMN "auth_user".username IS '用户名(唯一索引)';
COMMENT ON COLUMN "auth_user".email IS '邮箱地址';
COMMENT ON COLUMN "auth_user".password IS '加密后的密码';
COMMENT ON COLUMN "auth_user".nickname IS '用户昵称';
COMMENT ON COLUMN "auth_user".avatar_file_id IS '头像文件ID';
COMMENT ON COLUMN "auth_user".inviter IS '邀请人ID';
COMMENT ON COLUMN "auth_user".refresh_token IS '刷新令牌';
COMMENT ON COLUMN "auth_user".refresh_token_expire_at IS '刷新令牌过期时间';
COMMENT ON COLUMN "auth_user".updated_at IS '更新时间';
COMMENT ON COLUMN "auth_user".created_at IS '创建时间';

INSERT INTO "auth_user" (id, username, email, password, nickname, inviter)
VALUES (
    1,
    'DriftCloud',
    'mo.drift.cloud@gmail.com',
    '$argon2id$v=19$m=16384,t=2,p=1$B/FhuHJJ2X9jEO+Z14XiPg$gXNAPXP8draXlp+G6ZuQS+HpcufY+rke0nsfTk2HmiE',
    'DriftCloud',
    0
)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- Photo 模块
-- ============================================

-- 照片表
CREATE TABLE IF NOT EXISTS photo_photo
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    size                 BIGINT       NOT NULL DEFAULT 0,
    width                INTEGER      NOT NULL DEFAULT 0,
    height               INTEGER      NOT NULL DEFAULT 0,
    mime_type            VARCHAR(100) NOT NULL DEFAULT '',
    md5                  CHAR(32)     NULL,
    file_id              VARCHAR(255) NULL,
    comment_count        BIGINT       NOT NULL DEFAULT 0,
    like_count           BIGINT       NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- 唯一约束：直接使用 CREATE UNIQUE INDEX IF NOT EXISTS
CREATE UNIQUE INDEX IF NOT EXISTS uk_photo_file_id ON photo_photo (file_id);

-- 普通索引：幂等创建
-- 复合 (created_at, id) 使 keyset 分页排序直接走索引, 避免全表排序
CREATE INDEX IF NOT EXISTS idx_photo_created_at ON photo_photo (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_photo_md5 ON photo_photo (md5);
CREATE INDEX IF NOT EXISTS idx_photo_user_id ON photo_photo (user_id);
CREATE INDEX IF NOT EXISTS idx_photo_like_count ON photo_photo (like_count DESC);

COMMENT ON TABLE photo_photo IS '用户相册表';
COMMENT ON COLUMN photo_photo.id IS '主键ID';
COMMENT ON COLUMN photo_photo.user_id IS '上传者ID';
COMMENT ON COLUMN photo_photo.name IS '照片名称';
COMMENT ON COLUMN photo_photo.size IS '文件大小(字节)';
COMMENT ON COLUMN photo_photo.width IS '照片宽度(像素)';
COMMENT ON COLUMN photo_photo.height IS '照片高度(像素)';
COMMENT ON COLUMN photo_photo.mime_type IS '文件MIME类型';
COMMENT ON COLUMN photo_photo.md5 IS '文件MD5哈希值';
COMMENT ON COLUMN photo_photo.file_id IS '原始文件ID';
COMMENT ON COLUMN photo_photo.comment_count IS '评论总数';
COMMENT ON COLUMN photo_photo.like_count IS '点赞总数';
COMMENT ON COLUMN photo_photo.created_at IS '创建时间';
COMMENT ON COLUMN photo_photo.updated_at IS '更新时间';

-- 照片时间线统计表
CREATE TABLE IF NOT EXISTS photo_timeline_stat
(
    date_str    CHAR(7) NOT NULL PRIMARY KEY,
    count       BIGINT NOT NULL DEFAULT 0,
    anchor_time TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE photo_timeline_stat IS '照片时间线统计表';
COMMENT ON COLUMN photo_timeline_stat.date_str IS '数据字符串 格式为YYYY-MM';
COMMENT ON COLUMN photo_timeline_stat.count IS '照片数量';
COMMENT ON COLUMN photo_timeline_stat.anchor_time IS '最新一张照片的时间锚点';
COMMENT ON COLUMN photo_timeline_stat.created_at IS '创建时间';
COMMENT ON COLUMN photo_timeline_stat.updated_at IS '更新时间';

-- 1. 收藏夹主表 (文件夹)
CREATE TABLE IF NOT EXISTS photo_collection (
    id            BIGSERIAL PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   TEXT,
    photo_count   BIGINT DEFAULT 0 NOT NULL,
    cover_file_id VARCHAR,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE photo_collection IS '用户收藏夹表';
COMMENT ON COLUMN photo_collection.id IS '主键ID';
COMMENT ON COLUMN photo_collection.user_id IS '创建者用户ID';
COMMENT ON COLUMN photo_collection.name IS '收藏夹名称';
COMMENT ON COLUMN photo_collection.description IS '收藏夹详细描述';
COMMENT ON COLUMN photo_collection.photo_count IS '逻辑字段：统计该收藏夹下的图片总数';
COMMENT ON COLUMN photo_collection.cover_file_id IS '收藏夹封面图的文件ID';
COMMENT ON COLUMN photo_collection.created_at IS '创建时间';
COMMENT ON COLUMN photo_collection.updated_at IS '更新时间';

-- 2. 收藏关系表 (多对多)
CREATE TABLE IF NOT EXISTS photo_collection_photo (
    id            BIGSERIAL PRIMARY KEY,
    collection_id BIGINT NOT NULL,
    photo_id      BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_collection_photo UNIQUE (collection_id, photo_id)
);

COMMENT ON TABLE photo_collection_photo IS '收藏夹与图片的关联关系表';
COMMENT ON COLUMN photo_collection_photo.id IS '主键ID';
COMMENT ON COLUMN photo_collection_photo.collection_id IS '关联的收藏夹ID';
COMMENT ON COLUMN photo_collection_photo.photo_id IS '关联的图片ID';
COMMENT ON COLUMN photo_collection_photo.user_id IS '所属用户ID（用于越权检查）';
COMMENT ON COLUMN photo_collection_photo.created_at IS '收藏时间/创建时间';
COMMENT ON COLUMN photo_collection_photo.updated_at IS '关系更新时间';

-- 3. 物理索引 (幂等创建)
CREATE INDEX IF NOT EXISTS idx_collection_user_id ON photo_collection(user_id);
CREATE INDEX IF NOT EXISTS idx_fp_collection_id_created_id ON photo_collection_photo(collection_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_fp_photo_id ON photo_collection_photo (photo_id);

COMMENT ON INDEX idx_collection_user_id IS '优化：按用户查询收藏夹列表';
COMMENT ON INDEX idx_fp_collection_id_created_id IS '优化：按收藏时间倒序查询收藏夹内容（复合游标）';

-- 照片评论表
CREATE TABLE IF NOT EXISTS photo_comment (
    id         BIGSERIAL PRIMARY KEY,
    photo_id   BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    content    TEXT NOT NULL,
    like_count INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE photo_comment IS '照片评论表';
COMMENT ON COLUMN photo_comment.id IS '主键ID';
COMMENT ON COLUMN photo_comment.photo_id IS '照片ID';
COMMENT ON COLUMN photo_comment.user_id IS '评论者用户ID';
COMMENT ON COLUMN photo_comment.content IS '评论内容';
COMMENT ON COLUMN photo_comment.like_count IS '点赞总数统计';
COMMENT ON COLUMN photo_comment.created_at IS '创建时间';
COMMENT ON COLUMN photo_comment.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_comment_photo_time ON photo_comment (photo_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comment_photo_likes ON photo_comment (photo_id, like_count DESC);
CREATE INDEX IF NOT EXISTS idx_comment_user_id ON photo_comment (user_id);

COMMENT ON INDEX idx_comment_photo_time IS '优化：按照片查询评论';
COMMENT ON INDEX idx_comment_photo_likes IS '优化：按照片查询高赞评论';

-- 评论点赞记录表
CREATE TABLE IF NOT EXISTS photo_comment_like (
    id         BIGSERIAL PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_comment_user_like UNIQUE (comment_id, user_id)
);

COMMENT ON TABLE photo_comment_like IS '评论点赞记录表';
COMMENT ON COLUMN photo_comment_like.comment_id IS '评论ID';
COMMENT ON COLUMN photo_comment_like.user_id IS '点赞用户ID';
COMMENT ON COLUMN photo_comment_like.created_at IS '点赞时间';
COMMENT ON COLUMN photo_comment_like.updated_at IS '更新时间';

-- 照片点赞记录表
CREATE TABLE IF NOT EXISTS photo_photo_like (
    id         BIGSERIAL PRIMARY KEY,
    photo_id   BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_photo_user_like UNIQUE (photo_id, user_id)
);

COMMENT ON TABLE photo_photo_like IS '照片点赞记录表';
COMMENT ON COLUMN photo_photo_like.photo_id IS '照片ID';
COMMENT ON COLUMN photo_photo_like.user_id IS '点赞用户ID';
COMMENT ON COLUMN photo_photo_like.created_at IS '点赞时间';
COMMENT ON COLUMN photo_photo_like.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_photo_like_photo_id ON photo_photo_like (photo_id);
CREATE INDEX IF NOT EXISTS idx_photo_like_user_id ON photo_photo_like (user_id);
CREATE INDEX IF NOT EXISTS idx_photo_like_user_photo ON photo_photo_like (user_id, photo_id);

CREATE TABLE IF NOT EXISTS audit_event
(
    event_id     BIGINT PRIMARY KEY,
    event_type   VARCHAR(120) NOT NULL,
    actor_id     BIGINT NULL,
    target_type  VARCHAR(64) NULL,
    target_id    BIGINT NULL,
    detail       JSONB NULL,
    occurred_at  TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_event_type_occurred
    ON audit_event (event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_event_actor_occurred
    ON audit_event (actor_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_event_target_occurred
    ON audit_event (target_type, target_id, occurred_at DESC);

-- 向量扩展（幂等）
CREATE EXTENSION IF NOT EXISTS vector;

-- 人脸识别表
CREATE TABLE IF NOT EXISTS photo_face (
    id         BIGSERIAL PRIMARY KEY,
    photo_id   BIGINT NOT NULL,
    person_id  BIGINT NULL,
    bbox       JSONB NOT NULL,
    landmarks  JSONB NOT NULL,
    score      DOUBLE PRECISION NOT NULL,
    embedding  vector(512) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_photo_face_photo_id ON photo_face(photo_id);
CREATE INDEX IF NOT EXISTS idx_photo_face_person_id ON photo_face(person_id);

-- 人物表
CREATE TABLE IF NOT EXISTS photo_person (
    id             BIGSERIAL PRIMARY KEY,
    name           VARCHAR(32) NULL,
    name_initials  VARCHAR(32) NULL,
    cover_face_id  BIGINT NULL,
    cover_photo_id BIGINT NOT NULL,
    cover_file_id  VARCHAR(255) NOT NULL,
    cover_bbox     JSONB NOT NULL,
    centroid       vector(512) NOT NULL,
    face_count     BIGINT NOT NULL DEFAULT 0,
    weight         DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE photo_person IS '人物表(聚类结果)';
COMMENT ON COLUMN photo_person.id IS '主键ID';
COMMENT ON COLUMN photo_person.name IS '人物名称';
COMMENT ON COLUMN photo_person.name_initials IS '姓名首字母';
COMMENT ON COLUMN photo_person.cover_face_id IS '封面人脸ID(cluster 内 score 最高)';
COMMENT ON COLUMN photo_person.cover_photo_id IS '封面人脸所属照片ID(冗余自 photo_face.photo_id, 消除封面查询 N+1)';
COMMENT ON COLUMN photo_person.cover_file_id IS '封面照片 file_id(冗余自 photo_photo.file_id, 消除封面查询 N+1)';
COMMENT ON COLUMN photo_person.cover_bbox IS '封面人脸归一化 bbox(冗余自 photo_face.bbox, 消除封面查询 N+1)';
COMMENT ON COLUMN photo_person.centroid IS 'score 加权向量和 Σ(score*embedding), 未归一化, 读取时 normalize(增量维护)';
COMMENT ON COLUMN photo_person.face_count IS '人脸数量';
COMMENT ON COLUMN photo_person.weight IS '该人物所有人脸 score 之和(增量维护质心的权重)';
COMMENT ON COLUMN photo_person.created_at IS '创建时间';
COMMENT ON COLUMN photo_person.updated_at IS '更新时间';
