[package]
name = "backup"
version = "0.1.7"
edition = "2024"

[features]
default = []
metrics = ["common/metrics"]
audit = ["audit/recording"]

[dependencies]
audit.path = "../audit"
types = { path = "../../types", features = ["orm"] }
common = { path = "../../common", features = ["axum"] }
common_macros.path = "../../libs/common_macros"
oss.path = "../../libs/oss"

sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
csv.workspace = true
tokio-cron-scheduler.workspace = true
axum.workspace = true
