[package]
name = "backup"
version = "0.4.3"
edition = "2024"

[features]
default = []
metrics = ["oss/metrics"]
audit = ["audit/recording"]

[dependencies]
audit.path = "../audit"
types-core = { workspace = true, features = ["orm"] }
types-backup.workspace = true
common-core = { workspace = true }
common-db = { workspace = true }
common-metrics = { workspace = true }
common-runtime = { workspace = true }
common-web = { workspace = true }
common_macros.path = "../../libs/common_macros"
oss.path = "../../libs/oss"

sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-compression.workspace = true
futures-util.workspace = true
sqlx.workspace = true
bytes.workspace = true
axum.workspace = true
chrono.workspace = true
