[package]
name = "oss"
version = "0.5.0"
edition = "2024"

[features]
default = []
metrics = ["common/metrics"]

[dependencies]
common.path = "../../common"
serde.workspace = true
bytes.workspace = true
reqwest.workspace = true
s3.workspace = true
tokio.workspace = true
futures.workspace = true
thiserror.workspace = true
tracing.workspace = true
