[package]
name = "oss"
version = "0.1.2"
edition = "2024"

[features]
metrics = ["dep:metrics"]

[dependencies]
common = { path = "../../common" }
metrics = { workspace = true, optional = true }
serde = { workspace = true }
bytes = { workspace = true }
reqwest = { workspace = true }
s3 = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
