[package]
name = "oss"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common", features = ["s3"] }
serde = { workspace = true }
bytes = { workspace = true }
reqwest = { workspace = true }
s3 = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
