[package]
name = "auth"
version = "0.3.1"
edition = "2024"

[features]
default = []
metrics = ["common/metrics", "email/metrics"]
controller = ["dep:axum", "common/axum"]
audit = ["audit/recording"]

[dependencies]
audit = { path = "../audit" }
types-identity = { workspace = true, features = ["orm"] }
common = { path = "../../common", features = [
    "metrics",
    "tokio"
] }
common-metrics = { workspace = true }
constants.path = "../constants"
email.path = "../../libs/email"
common_macros.path = "../../libs/common_macros"

tokio.workspace = true
tracing.workspace = true
sea-orm.workspace = true
axum = { workspace = true, optional = true }
