[package]
name = "auth"
version = "0.2.0"
edition = "2024"

[features]
default = []
metrics = ["common/metrics", "dep:metrics"]
controller = ["dep:axum"]
audit = ["audit/enable"]

[dependencies]
audit = { path = "../audit" }
types = { workspace = true, features = ["orm"] }
common = { path = "../../common", features = [
    "validators",
    "metrics",
    "contextual-sea-orm",
    "contextual-redis",
    "contextual-tokio",
] }
constants = { path = "../constants" }
sea-orm = { workspace = true }
email = { path = "../../libs/email" }
deadpool-redis = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

axum = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }
