[package]
name = "auth"
version = "0.2.0"
edition = "2024"

[features]
default = []
metrics = ["common/metrics", "dep:metrics"]
controller = ["dep:axum"]
audit = ["audit/recording"]

[dependencies]
# 审计
audit = { path = "../audit" }
# 类型
types = { workspace = true, features = ["orm"] }
common = { path = "../../common", features = [
    "validators",
    "metrics",
    "contextual-sea-orm",
    "contextual-redis",
    "contextual-tokio",
] }
constants.path = "../constants"
email.path = "../../libs/email"
tokio = { workspace = true }
tracing = { workspace = true }

axum = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }
sea-orm = { workspace = true }
