[package]
name = "server"
version = "0.1.4"
edition = "2024"

[[bin]]
name = "memory-seek-server"
path = "src/main.rs"

[features]
default = []
token_cipher = []
auth = ["dep:auth", "email", "token_cipher"]
user = ["dep:user", "s3", "token_cipher"]
photo = ["dep:photo", "s3", "token_cipher"]

email = ["dep:email"]
metrics = ["common/metrics", "dep:metrics", "photo?/metrics", "user?/metrics", "auth?/metrics", "email?/metrics", "oss?/metrics", "backup?/metrics"]
s3 = ["dep:oss"]
backup = ["dep:backup"]
face-engine = ["dep:insight-face-rs", "photo/face", "backup"]

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
serde = { workspace = true }
serde_json = { workspace = true }
tower-http = { version = "0.6", features = ["cors", "trace"] }

# 业务模块
auth = { path = "../domains/auth", features = ["controller"], optional = true }
user = { path = "../domains/user", features = ["controller"], optional = true }
photo = { path = "../domains/photo", features = ["controller"], optional = true }
backup = { path = "../domains/backup", optional = true }

# 基础设施
common = { path = "../common" }
constants = { path = "../domains/constants" }
types = { path = "../types", features = ["orm"] }
email = { path = "../libs/email", optional = true }
config = { workspace = true }
dotenvy = { workspace = true }
clap = { workspace = true }

# 性能监控
metrics = { workspace = true, optional = true }
sysinfo = "0.31"
metrics-exporter-prometheus = "0.16"

# S3
oss = { path = "../libs/oss", optional = true }

# 数据库
sea-orm = { workspace = true }
redis = { workspace = true }
deadpool-redis = { workspace = true }

# UUID
uuid = { workspace = true }
metrics-tracing-context = "0.18.1"
insight-face-rs = { optional = true, workspace = true }
tikv-jemallocator = "0.7.0"
