[package]
name = "audit"
version = "0.3.0"
edition = "2024"

[features]
default = []
recording = ["dep:common-crypto"]
metrics = []
controller = ["dep:axum", "dep:common-web"]

[dependencies]
common-core = { workspace = true }
common-metrics = { workspace = true }
common-crypto = { workspace = true, optional = true }
common-web = { workspace = true, optional = true }
types-core = { workspace = true, features = ["orm"] }
types-audit = { workspace = true, features = ["orm"] }
common_macros.path = "../../libs/common_macros"

# controller 需要
axum = { workspace = true, optional = true }

# mapper 需要
sea-orm = { workspace = true }

# metrics 埋点需要
tracing.workspace = true
