[package]
name = "audit"
version = "0.1.0"
edition = "2024"

[features]
default = []
persistence = []
controller = ["dep:axum"]

[dependencies]
common = { path = "../../common", features = ["contextual-sea-orm", "validators"] }
chrono = { workspace = true }
sea-orm = { workspace = true }
serde_json = { workspace = true }
types = { path = "../../types", features = ["orm"] }
axum = { workspace = true, optional = true }
