[package]
name = "visual"
version = "0.10.0"
edition = "2024"

[features]
default = []
metrics = ["multi-level-cache/metrics", "oss/metrics"]
controller = ["dep:axum", "dep:common-web"]
audit = ["audit/recording"]
face = ["dep:insight-face-rs", "dep:backup", "types-visual/face-engine"]
ts = ["types-visual/ts", "common-core/ts"]

[dependencies]
common-core = { workspace = true, features = [
    "multi-cache",
    "tokio"
] }
common-redis = { workspace = true }
common-db = { workspace = true }
common-metrics = { workspace = true }
common-runtime = { workspace = true }
common-web = { workspace = true, optional = true }
file-validator.path = "../../libs/file_validator"
common_macros.path = "../../libs/common_macros"
audit.path = "../audit"
step_derive.path = "../../libs/step_derive"
constants.path = "../constants"
oss.path = "../../libs/oss"
types-core = { workspace = true, features = ["orm"] }
types-identity = { workspace = true }
types-visual = { workspace = true, features = ["orm"] }

linkme.workspace = true
async-trait.workspace = true

tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
sea-orm.workspace = true
tracing.workspace = true
blake3.workspace = true
uuid.workspace = true
futures.workspace = true
multi-level-cache.workspace = true
bytes.workspace = true
image.workspace = true
pinyin.workspace = true
petal-clustering = "0.13.0"
ndarray = "0.17.2"

axum = { workspace = true, optional = true }
insight-face-rs = { workspace = true, optional = true }
backup = { path = "../backup", optional = true }
