-- Memory Seek 数据库初始化脚本
-- 合并 auth 和 photo 模块的所有表结构

-- ============================================
-- Auth 模块
-- ============================================

create table if not exists "auth_user"
(
    id                      BIGSERIAL PRIMARY KEY ,
    username                varchar(255) not null,
    email                   varchar(255) not null,
    password                varchar(255) not null,
    nickname                varchar(255) not null,
    avatar_file_id          varchar(2000) null,
    inviter                 bigint not null,
    refresh_token           char(32) null,
    refresh_token_expire_at TIMESTAMPTZ null,
    updated_at              TIMESTAMPTZ DEFAULT NOW() not null,
    created_at              TIMESTAMPTZ DEFAULT NOW() not null,
    constraint user_username_index unique (username),
    constraint user_email_index unique (email)
    );
COMMENT ON TABLE "auth_user" IS '用户表';
COMMENT ON COLUMN "auth_user".id IS '主键ID';
COMMENT ON COLUMN "auth_user".username IS '用户名(唯一索引)';
COMMENT ON COLUMN "auth_user".email IS '邮箱地址';
COMMENT ON COLUMN "auth_user".password IS '加密后的密码';
COMMENT ON COLUMN "auth_user".nickname IS '用户昵称';
COMMENT ON COLUMN "auth_user".avatar_file_id IS '头像文件ID';
COMMENT ON COLUMN "auth_user".inviter IS '邀请人ID';
COMMENT ON COLUMN "auth_user".refresh_token IS '刷新令牌';
COMMENT ON COLUMN "auth_user".refresh_token_expire_at IS '刷新令牌过期时间';
COMMENT ON COLUMN "auth_user".updated_at IS '更新时间';
COMMENT ON COLUMN "auth_user".created_at IS '创建时间';

-- ============================================
-- Photo 模块
-- ============================================

-- 照片表
CREATE TABLE IF NOT EXISTS photo_photo
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id              BIGINT       NOT NULL,
    name                 VARCHAR(255) NOT NULL,

    size                 BIGINT       NOT NULL DEFAULT 0,
    width                INTEGER      NOT NULL DEFAULT 0,
    height               INTEGER      NOT NULL DEFAULT 0,
    mime_type            VARCHAR(100) NOT NULL DEFAULT '',

    md5                  CHAR(32)     NULL,
    file_id              VARCHAR(255) NULL,

    comment_count        BIGINT       NOT NULL DEFAULT 0,

    -- 时间记录
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- 唯一约束：确保 file_id 不重复
CREATE UNIQUE INDEX uk_photo_file_id ON photo_photo (file_id);
CREATE INDEX idx_photo_created_at ON "photo_photo" (created_at DESC);
-- 哈希索引：用于秒传/去重
CREATE INDEX idx_photo_md5 ON photo_photo (md5);
CREATE INDEX idx_photo_user_id ON photo_photo (user_id);
COMMENT ON TABLE photo_photo IS '用户相册表';
COMMENT ON COLUMN photo_photo.id IS '主键ID';
COMMENT ON COLUMN photo_photo.user_id IS '上传者ID';
COMMENT ON COLUMN photo_photo.name IS '照片名称';
COMMENT ON COLUMN photo_photo.size IS '文件大小(字节)';
COMMENT ON COLUMN photo_photo.width IS '照片宽度(像素)';
COMMENT ON COLUMN photo_photo.height IS '照片高度(像素)';
COMMENT ON COLUMN photo_photo.mime_type IS '文件MIME类型';
COMMENT ON COLUMN photo_photo.md5 IS '文件MD5哈希值';
COMMENT ON COLUMN photo_photo.file_id IS '原始文件ID';
COMMENT ON COLUMN photo_photo.comment_count IS '评论总数';
COMMENT ON COLUMN photo_photo.created_at IS '创建时间';
COMMENT ON COLUMN photo_photo.updated_at IS '更新时间';

-- 照片时间线统计表
create table if not exists photo_timeline_stat
(
    date_str char(7) NOT NULL PRIMARY KEY,
    count BIGINT NOT NULL DEFAULT 0,
    anchor_time TIMESTAMPTZ NOT NULL,

    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE photo_timeline_stat IS '照片时间线统计表';
COMMENT ON COLUMN photo_timeline_stat.date_str IS '数据字符串 格式为YYYY-MM';
COMMENT ON COLUMN photo_timeline_stat.count IS '照片数量';
COMMENT ON COLUMN photo_timeline_stat.anchor_time IS '最新一张照片的时间锚点';
COMMENT ON COLUMN photo_timeline_stat.created_at IS '创建时间';
COMMENT ON COLUMN photo_timeline_stat.updated_at IS '更新时间';

-- 1. 收藏夹主表 (文件夹)
CREATE TABLE IF NOT EXISTS photo_collection (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    photo_count BIGINT DEFAULT 0 NOT NULL,
    cover_file_id VARCHAR,
    is_favorite BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 表与字段注释
COMMENT ON TABLE photo_collection IS '用户收藏夹表';
COMMENT ON COLUMN photo_collection.id IS '主键ID';
COMMENT ON COLUMN photo_collection.user_id IS '创建者用户ID';
COMMENT ON COLUMN photo_collection.name IS '收藏夹名称';
COMMENT ON COLUMN photo_collection.description IS '收藏夹详细描述';
COMMENT ON COLUMN photo_collection.photo_count IS '逻辑字段：统计该收藏夹下的图片总数';
COMMENT ON COLUMN photo_collection.cover_file_id IS '收藏夹封面图的文件ID';
COMMENT ON COLUMN photo_collection.is_favorite IS '是否为我喜欢';
COMMENT ON COLUMN photo_collection.created_at IS '创建时间';
COMMENT ON COLUMN photo_collection.updated_at IS '更新时间';

-- 2. 收藏关系表 (多对多)
CREATE TABLE IF NOT EXISTS photo_collection_photo (
    id BIGSERIAL PRIMARY KEY,
    collection_id BIGINT NOT NULL,
    photo_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    -- 唯一索引：防止同一张图在同一收藏夹重复
    CONSTRAINT uk_collection_photo UNIQUE (collection_id, photo_id)
);

-- 表与字段注释
COMMENT ON TABLE photo_collection_photo IS '收藏夹与图片的关联关系表';
COMMENT ON COLUMN photo_collection_photo.id IS '主键ID';
COMMENT ON COLUMN photo_collection_photo.collection_id IS '关联的收藏夹ID';
COMMENT ON COLUMN photo_collection_photo.photo_id IS '关联的图片ID';
COMMENT ON COLUMN photo_collection_photo.user_id IS '所属用户ID（用于越权检查）';
COMMENT ON COLUMN photo_collection_photo.created_at IS '收藏时间/创建时间';
COMMENT ON COLUMN photo_collection_photo.updated_at IS '关系更新时间';

-- 3. 物理索引 (优化查询)
CREATE INDEX idx_collection_user_id ON photo_collection(user_id);
CREATE INDEX idx_fp_collection_id_created_id ON photo_collection_photo(collection_id, created_at DESC, id DESC);
CREATE INDEX idx_fp_photo_id ON photo_collection_photo (photo_id);
COMMENT ON INDEX idx_collection_user_id IS '优化：按用户查询收藏夹列表';
COMMENT ON INDEX idx_fp_collection_id_created_id IS '优化：按收藏时间倒序查询收藏夹内容（复合游标）';

-- 照片评论表
CREATE TABLE IF NOT EXISTS photo_comment (
     id BIGSERIAL PRIMARY KEY,
     photo_id BIGINT NOT NULL,
     user_id BIGINT NOT NULL,
     content TEXT NOT NULL,
     like_count integer DEFAULT 0 NOT NULL, -- 冗余字段：点赞总数，方便展示
     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE photo_comment IS '照片评论表';
COMMENT ON COLUMN photo_comment.id IS '主键ID';
COMMENT ON COLUMN photo_comment.photo_id IS '照片ID';
COMMENT ON COLUMN photo_comment.user_id IS '评论者用户ID';
COMMENT ON COLUMN photo_comment.content IS '评论内容';
COMMENT ON COLUMN photo_comment.like_count IS '点赞总数统计';
COMMENT ON COLUMN photo_comment.created_at IS '创建时间';
COMMENT ON COLUMN photo_comment.updated_at IS '更新时间';

-- 索引：按照片和时间快速加载评论
CREATE INDEX idx_comment_photo_time ON photo_comment (photo_id, created_at DESC);
COMMENT ON INDEX idx_comment_photo_time IS '优化：按照片查询评论';

CREATE INDEX idx_comment_photo_likes ON photo_comment (photo_id, like_count DESC);
COMMENT ON INDEX idx_comment_photo_likes IS '优化：按照片查询高赞评论';

CREATE INDEX idx_comment_user_id ON photo_comment (user_id);

-- 评论点赞记录表
CREATE TABLE IF NOT EXISTS photo_comment_like (
    id BIGSERIAL PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 唯一索引：防止重复点赞
    CONSTRAINT uk_comment_user_like UNIQUE (comment_id, user_id)
);

COMMENT ON TABLE photo_comment_like IS '评论点赞记录表';
COMMENT ON COLUMN photo_comment_like.comment_id IS '评论ID';
COMMENT ON COLUMN photo_comment_like.user_id IS '点赞用户ID';
COMMENT ON COLUMN photo_comment_like.created_at IS '点赞时间';
COMMENT ON COLUMN photo_comment_like.updated_at IS '更新时间';

