[package]
name = "bench-support"
version = "0.1.3"
edition = "2024"

[dependencies]
common = { path = "../../common", features = ["contextual-cache"] }
oss = { path = "../../libs/oss" }
criterion = { workspace = true }
deadpool-redis = { workspace = true }
redis = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
multi-level-cache.workspace = true
