-- 照片表
CREATE TABLE IF NOT EXISTS photo_photo
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id              BIGINT       NOT NULL,
    name                 VARCHAR(255) NOT NULL,

    size                 BIGINT       NOT NULL DEFAULT 0,
    width                INTEGER      NOT NULL DEFAULT 0,
    height               INTEGER      NOT NULL DEFAULT 0,
    mime_type            VARCHAR(100) NOT NULL DEFAULT '',

    md5                  CHAR(32)     NULL,
    file_id              VARCHAR(255) NULL,

    -- 时间记录
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- 唯一约束：确保 file_id 不重复
CREATE UNIQUE INDEX uk_photo_file_id ON photo_photo (file_id);
CREATE INDEX idx_photo_created_at ON "photo_photo" (created_at DESC);
-- 哈希索引：用于秒传/去重
CREATE INDEX idx_photo_md5 ON photo_photo (md5);
COMMENT ON TABLE photo_photo IS '用户相册表';
COMMENT ON COLUMN photo_photo.id IS '主键ID';
COMMENT ON COLUMN photo_photo.user_id IS '上传者ID';
COMMENT ON COLUMN photo_photo.name IS '照片名称';
COMMENT ON COLUMN photo_photo.size IS '文件大小(字节)';
COMMENT ON COLUMN photo_photo.width IS '照片宽度(像素)';
COMMENT ON COLUMN photo_photo.height IS '照片高度(像素)';
COMMENT ON COLUMN photo_photo.mime_type IS '文件MIME类型';
COMMENT ON COLUMN photo_photo.md5 IS '文件MD5哈希值';
COMMENT ON COLUMN photo_photo.file_id IS '原始文件ID';
COMMENT ON COLUMN photo_photo.created_at IS '创建时间';
COMMENT ON COLUMN photo_photo.updated_at IS '更新时间';

-- 照片时间线统计表
create table if not exists photo_timeline_stat
(
    date_str char(7) NOT NULL PRIMARY KEY,
    count BIGINT NOT NULL DEFAULT 0,
    anchor_time TIMESTAMPTZ NOT NULL,

    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE photo_timeline_stat IS '照片时间线统计表';
COMMENT ON COLUMN photo_timeline_stat.date_str IS '数据字符串 格式为YYYY-MM';
COMMENT ON COLUMN photo_timeline_stat.count IS '照片数量';
COMMENT ON COLUMN photo_timeline_stat.anchor_time IS '最新一张照片的时间锚点';
COMMENT ON COLUMN photo_timeline_stat.created_at IS '创建时间';
COMMENT ON COLUMN photo_timeline_stat.updated_at IS '更新时间';

INSERT INTO photo_timeline_stat (date_str, count, anchor_time, created_at, updated_at)
SELECT
    TO_CHAR(photo_photo.created_at, 'YYYY-MM') as d_str,
    COUNT(*) as cnt,
    MAX(photo_photo.created_at) as anchor,
    NOW(),
    NOW()
FROM photo_photo
GROUP BY d_str
ON CONFLICT (date_str)
DO UPDATE SET
    count = EXCLUDED.count,
    anchor_time = EXCLUDED.anchor_time,
    updated_at = NOW();

