[package]
name = "photo"
version = "0.2.3"
edition = "2024"

[features]
default = []
metrics = ["common/metrics", "dep:metrics", "oss/metrics", "multi-level-cache/metrics"]
controller = ["dep:axum"]
audit = ["audit/recording"]
file_validator = ["common/file_validator"]
face = ["dep:insight-face-rs", "dep:backup", "types/face-engine"]
# TypeScript 类型导出
ts = ["types/ts", "common/ts"]

[dependencies]
common = { path = "../../common", features = [
    "validators",
    "file_validator",
    "metrics",
    "contextual-sea-orm",
    "contextual-cache",
    "contextual-serde",
    "contextual-tokio",
    "event",
] }
audit = { path = "../audit" }
async-trait = { workspace = true }
step_derive = { path = "../../libs/step_derive" }
linkme = { workspace = true }
constants = { path = "../constants" }

oss = { path = "../../libs/oss" }

axum = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sea-orm = { workspace = true }
tracing = { workspace = true }
md5 = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
multi-level-cache.workspace = true
bytes = { workspace = true }
insight-face-rs = { workspace = true, optional = true }
backup = { path = "../backup", optional = true }
image.workspace = true
types = { workspace = true, features = ["full"] }
pinyin = { workspace = true }
petal-clustering = "0.13.0"
ndarray = "0.17.2"
