[package]
name = "photo"
version = "0.2.3"
edition = "2024"

[features]
default = []
metrics = ["common/metrics", "multi-level-cache/metrics"]
controller = ["dep:axum"]
audit = ["audit/recording"]
face = ["dep:insight-face-rs", "dep:backup", "types/face-engine"]
ts = ["types/ts", "common/ts"]

[dependencies]
common = { path = "../../common", features = [
    "validators",
    "file_validator",
    "metrics",
    "contextual-sea-orm",
    "contextual-cache",
    "contextual-serde",
    "contextual-tokio",
    "event",
] }
audit.path = "../audit"
step_derive.path = "../../libs/step_derive"
constants.path = "../constants"
oss.path = "../../libs/oss"
types = { workspace = true, features = ["full"] }

linkme.workspace = true
async-trait.workspace = true

tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
sea-orm.workspace = true
tracing.workspace = true
md5.workspace = true
uuid.workspace = true
futures.workspace = true
multi-level-cache.workspace = true
bytes.workspace = true
image.workspace = true
pinyin.workspace = true
petal-clustering = "0.13.0"
ndarray = "0.17.2"

axum = { workspace = true, optional = true }
insight-face-rs = { workspace = true, optional = true }
backup = { path = "../backup", optional = true }
