[package]
name = "user"
version = "0.5.0"
edition = "2024"

[features]
default = []
metrics = ["multi-level-cache/metrics", "oss/metrics"]
controller = ["dep:axum", "dep:common-web"]
audit = ["audit/recording"]

[dependencies]
common-core = { workspace = true, features = [
    "multi-cache",
    "tokio"
] }
common-cache = { workspace = true }
common-crypto = { workspace = true }
common-db = { workspace = true }
common-metrics = { workspace = true }
common-web = { workspace = true, optional = true }
file-validator.path = "../../libs/file_validator"
common_macros.path = "../../libs/common_macros"
audit.path = "../audit"
constants.path = "../constants"
oss.path = "../../libs/oss"
types-identity = { workspace = true, features = ["orm"] }
types-token.workspace = true

multi-level-cache.workspace = true
serde.workspace = true
sea-orm.workspace = true
uuid.workspace = true
redis.workspace = true
tracing.workspace = true
tokio.workspace = true
bytes.workspace = true

axum = { workspace = true, optional = true }
