[package]
name = "user"
version = "0.1.21"
edition = "2024"

[features]
default = []
metrics = ["common/metrics", "dep:metrics", "oss/metrics", "multi-level-cache/metrics"]
controller = ["dep:axum"]
audit = ["audit/recording"]

[dependencies]
common = { path = "../../common", features = [
    "file_validator",
    "validators",
    "metrics",
    "contextual-sea-orm",
    "contextual-redis",
    "contextual-cache",
    "contextual-tokio",
] }
audit = { path = "../audit" }
constants = { path = "../constants" }
types = { workspace = true, features = ["orm"] }
oss = { path = "../../libs/oss" }
serde = { workspace = true }
sea-orm = { workspace = true }
redis = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }
bytes.workspace = true
multi-level-cache.workspace = true
